version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_desafio_backend
    environment:
      POSTGRES_DB: desafio_backend_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desafio_backend_network

volumes:
  postgres_data:

networks:
  desafio_backend_network:
    driver: bridge
